stages:
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  tags:
    - pi
  script:
    - echo "Building project..."
    - gcc -o main main.c
  artifacts:
    paths:
      - main

test:
  stage: test
  tags:
    - pi
  script:
    - echo "Running tests..."
    - ./main
